/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;
import Errores.*;
import ejercicio3.Ejercicio3;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
public class VentanaPersona extends javax.swing.JFrame {
    public boolean modificar = false;
    public boolean borrar=false;
    public boolean iguales=false;
    public VentanaPersona() {
        initComponents();
        Eliminar.setVisible(false);
        Cambiar.setVisible(false);
        Nombre.setEnabled(false);
        Apellidos.setEnabled(false);
        Curso.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Apellidos = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Cambiar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Curso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Personas");

        jLabel2.setText("DNI:");

        DNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DNIFocusLost(evt);
            }
        });

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosActionPerformed(evt);
            }
        });

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Cambiar.setText("Cambiar");
        Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        jLabel5.setText("Curso:");

        Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                        .addComponent(Apellidos)
                                        .addComponent(Curso))
                                    .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Aceptar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Eliminar)
                            .addComponent(Cambiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Eliminar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cambiar))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Aceptar)
                    .addComponent(Salir))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidosActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Ejercicio3.terminar();
    }//GEN-LAST:event_SalirActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
      iguales=Ejercicio3.revisar_dni(iguales, DNI.getText());
        
        if (iguales=true)
        {
           mostrarDatos();
           Eliminar.setVisible(true);
           Cambiar.setVisible(true);
        }
       else
       { 
            Nombre.setEnabled(true);
            Apellidos.setEnabled(true);
            Curso.setEnabled(true);
            alta();
       }
    }//GEN-LAST:event_AceptarActionPerformed
private void alta(){ 
    try{
          validarDni();
          
          if (Ejercicio3.validarDni(DNI.getText()))          
          {
              mostrarDatos();
          }
          else
          {
            Aceptar.setEnabled(true);
            Nombre.requestFocus();
          }
          DNI.setEditable(false);
              
      }
      catch(DatoObligatorio e){
          javax.swing.JOptionPane.showMessageDialog(this,"El dni es un dato obligatorio");
          DNI.requestFocus();
      }
      catch(DniNoValido e){
          javax.swing.JOptionPane.showMessageDialog(this,"El dni no es correcto");
          DNI.requestFocus();
      }
      catch(Exception e){
          javax.swing.JOptionPane.showMessageDialog(this,"Problemas validando el dni");
      }
}
    private void CambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarActionPerformed
        Nombre.setEnabled(true);
        Apellidos.setEnabled(true);
        Curso.setEnabled(true);
        modificar=true;
        if (modificar=true)
        {
            modificar();
        }
    }//GEN-LAST:event_CambiarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        borrar=true;
        if (borrar=true)
        {
            borrar();
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CursoActionPerformed

    private void DNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DNIFocusLost
         try{
                validarDni();
                DNI.setEditable(false);  
            }
         
      catch(DatoObligatorio e){
          javax.swing.JOptionPane.showMessageDialog(this,"El dni es un dato obligatorio");
          DNI.requestFocus();
      }
      catch(DniNoValido e){
          javax.swing.JOptionPane.showMessageDialog(this,"El dni no es correcto");
          DNI.requestFocus();
      }
      catch(Exception e){
          javax.swing.JOptionPane.showMessageDialog(this,"Problemas validando el dni");
      }
    }//GEN-LAST:event_DNIFocusLost
private void validarDni() throws Exception {
        if (DNI.getText().isEmpty())
              throw new DatoObligatorio();
        
        Pattern pattern=Pattern.compile("(\\d{8})([TRWAGMYFPDXBNJZSQVHLCKEtrwagmyfpdxbnjzsqvhlcke])");
        Matcher matcher=pattern.matcher(DNI.getText());
        if(matcher.matches()){
            String letra=matcher.group(2);
            String letras="TRWAGMYFPDXBNJZSQVHLCKE";
            int numero=Integer.parseInt(matcher.group(1));
            numero=numero%23;
            String reference=letras.substring(numero,numero+1);
            if(!reference.equalsIgnoreCase(letra))
                throw new DniNoValido();
         }
        else
            throw new DniNoValido();
    }
    
    private void borrar() {
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, "¿Estas segur@? Ten en cuenta que los datos se eliminarán definitivamente.");
        if (respuesta == 0)
            Ejercicio3.borrarPersona();
        else
            Ejercicio3.volverEmpezar();
}

    private void modificar() {
    try{
         if (Curso.getText().isEmpty())
             throw new DatoObligatorio();
         if (Ejercicio3.validarCurso(Curso.getText()) == false)
             throw new CursoNoValido();
         Ejercicio3.modificarPersona();
         
     }
     catch(DatoObligatorio e){
          javax.swing.JOptionPane.showMessageDialog(this,"Todos los datos de entrada son obligatorios");
          Curso.requestFocus();
      }
     catch(CursoNoValido e){
         javax.swing.JOptionPane.showMessageDialog(this,"El curso tecleado no existe");
         Curso.requestFocus();
     }
     catch(Exception e){
         javax.swing.JOptionPane.showMessageDialog(this,"Problemas en el botón modificar");
    }
}

    public void mostrarDatos(){
        Nombre.setText(Ejercicio3.getPersona().getNombre());
        Nombre.setEnabled(false);
        Apellidos.setText(Ejercicio3.getPersona().getApellidos());
        Apellidos.setEnabled(false);
        Curso.setText(Ejercicio3.getPersona().getC().getCurso());   
        Curso.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextField Apellidos;
    private javax.swing.JButton Cambiar;
    private javax.swing.JTextField Curso;
    private javax.swing.JTextField DNI;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
