/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ejercicio1.Ejercicio1;

/**
 *
 * @author Asus
 */
public class VentanaEditarAñadirBorrar extends javax.swing.JFrame {

    /**
     * Creates new form MostrarDatos
     */
    public VentanaEditarAñadirBorrar() {
        initComponents();
    }
    private String valor;
    private String tipo;
    private String clase;
    private String genero;
    private String estadoC;
    private String contrato;
    private boolean cambio=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private String establecerTipo(String clase)
    {
        clase=Ejercicio1.establecerTipo(clase);
        return clase;
    }
    
    private void generar()
    {
        if(clase=="modificar" || clase=="borrar"){
            NSS.setEnabled(false);
            Direccion.setEnabled(false);
            Hombre.setEnabled(false);
            Mujer.setEnabled(false);
            Casado.setEnabled(false);
            Soltera.setEnabled(false);
            Fecha_alta.setEnabled(false);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        estadoCivil = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Nombre_apellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NSS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Hombre = new javax.swing.JRadioButton();
        Mujer = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Casado = new javax.swing.JRadioButton();
        Soltera = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Contrato = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Fecha_alta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        NumeroEmpleado = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DNI");

        DNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNIActionPerformed(evt);
            }
        });

        jLabel2.setText(" Nombres y apellidos");

        Nombre_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_apellidosActionPerformed(evt);
            }
        });

        jLabel3.setText("NSS");

        NSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NSSActionPerformed(evt);
            }
        });

        jLabel4.setText("Dirección");

        jLabel5.setText("Sexo");

        sexo.add(Hombre);
        Hombre.setText("Hombre");
        Hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HombreActionPerformed(evt);
            }
        });

        sexo.add(Mujer);
        Mujer.setText("Mujer");
        Mujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MujerActionPerformed(evt);
            }
        });

        jLabel6.setText("Estado Civil");

        Casado.setText("Casad@");
        Casado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasadoActionPerformed(evt);
            }
        });

        Soltera.setText("Solter@");
        Soltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolteraActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de contrato");

        Contrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratoActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha de alta");

        jLabel9.setText("Numero empleado");

        NumeroEmpleado.setEnabled(false);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nombre_apellidos)
                            .addComponent(DNI)
                            .addComponent(NSS)
                            .addComponent(Direccion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Hombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Mujer))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Casado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(Soltera))
                            .addComponent(Contrato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fecha_alta)
                            .addComponent(NumeroEmpleado)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancelar)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Hombre)
                    .addComponent(Mujer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Casado)
                    .addComponent(Soltera))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Fecha_alta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNIActionPerformed
        
    }//GEN-LAST:event_DNIActionPerformed

    private void Nombre_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_apellidosActionPerformed

    private void NSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NSSActionPerformed

    private void ContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContratoActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
    if(clase.equals("alta"))    
        Ejercicio1.validar(tipo, valor,DNI.getText(),Nombre_apellidos.getText(),NSS.getText(),Fecha_alta.getText(),genero,estadoC);
   
    if(clase.equals("modificar"))
        {
          cambio=Ejercicio1.revisar(cambio,tipo, valor,DNI.getText(),Nombre_apellidos.getText());
            if(cambio=true)
            {
                NSS.setEnabled(true);
                Direccion.setEnabled(true);
                Hombre.setEnabled(true);
                Mujer.setEnabled(true);
                Casado.setEnabled(true);
                Soltera.setEnabled(true);
                Fecha_alta.setEnabled(true);
            }
        }
    
    if(cambio=true&&clase.equals("modificar"))
        {
            Ejercicio1.validar2(Nombre_apellidos.getText(),NSS.getText(),Fecha_alta.getText(),genero,estadoC);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void HombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HombreActionPerformed
        genero="hombre";
    }//GEN-LAST:event_HombreActionPerformed

    private void MujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MujerActionPerformed
       genero="mujer";
    }//GEN-LAST:event_MujerActionPerformed

    private void CasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasadoActionPerformed
       if("hombre".equals(genero)) 
           estadoC="casado";
       if("mujer".equals(genero)) 
           estadoC="casada";   
    }//GEN-LAST:event_CasadoActionPerformed

    private void SolteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolteraActionPerformed
        if("hombre".equals(genero)) 
           estadoC="soltero";
       if("mujer".equals(genero)) 
           estadoC="soltera";
    }//GEN-LAST:event_SolteraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarAñadirBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarAñadirBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarAñadirBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarAñadirBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEditarAñadirBorrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JRadioButton Casado;
    private javax.swing.JComboBox<String> Contrato;
    private javax.swing.JTextField DNI;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Fecha_alta;
    private javax.swing.JRadioButton Hombre;
    private javax.swing.JRadioButton Mujer;
    private javax.swing.JTextField NSS;
    private javax.swing.JTextField Nombre_apellidos;
    private javax.swing.JTextField NumeroEmpleado;
    private javax.swing.JRadioButton Soltera;
    private javax.swing.ButtonGroup estadoCivil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup sexo;
    // End of variables declaration//GEN-END:variables
}
